services:
  floofy-sun:
    build: .
    container_name: floofy-sun
    restart: unless-stopped
    networks:
      - reverse-proxy
    volumes:
      - ./sites:/srv/sites
    environment:
      - FLOOFY_ROOT_DOMAIN=lab.devi.tools
      - FLOOFY_ADMIN_HOST=floofy.lab.devi.tools
      - FLOOFY_SITES_DIR=/srv/sites
      - FLOOFY_LISTEN=:8080
      - VIRTUAL_HOST=~^([a-z0-9-]+\.)?lab\.devi\.tools$$
      - VIRTUAL_PORT=8080
      - CERT_NAME=lab.devi.tools

networks:
  reverse-proxy:
    external: true
