version: '3.7'

services:
  lab:
    build:
      context: ..
      dockerfile: server/Dockerfile
    container_name: lab
    restart: unless-stopped
    networks:
      - reverse-proxy
    environment:
      - LAB_ROOT_DOMAIN=devi.tools
      - LAB_ADMIN_HOST=lab.devi.tools
      - LAB_LISTEN=:8080
      - VIRTUAL_HOST=~^[a-z0-9-]+\.devi\.tools$$
      - VIRTUAL_PORT=8080
      - CERT_NAME=wildcard

networks:
  reverse-proxy:
    external: true
