services:
  floofy-sun:
    build: .
    container_name: floofy-sun
    restart: unless-stopped
    networks:
      - reverse-proxy
    volumes:
      - ./sites:/srv/sites
    environment:
      - FLOOFY_ROOT_DOMAIN=devi.tools
      - FLOOFY_ADMIN_HOST=floofy.devi.tools
      - FLOOFY_SITES_DIR=/srv/sites
      - FLOOFY_LISTEN=:8080
      - VIRTUAL_HOST=~^[a-z0-9-]+\.devi\.tools$$
      - VIRTUAL_PORT=8080
      - CERT_NAME=wildcard

networks:
  reverse-proxy:
    external: true
